webtalk_init -webtalk_dir E:\\software\\Assessment_2_Traffic_Light_Ad4.0\\es3_hw_assmnt_2\\es3_hw_assmnt_2.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "星期四 十一月 24 00:44:21 2016" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2015.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2015.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "p8lqs9di14ds800k2gmqfs7eo4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2015.2_15" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "15" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1479935692366" -context "sdk\\\\hardware/1479935692366"
webtalk_add_data -client sdk -key isZynq -value "false" -context "sdk\\\\hardware/1479935692366"
webtalk_add_data -client sdk -key Processors -value "1" -context "sdk\\\\hardware/1479935692366"
webtalk_add_data -client sdk -key VivadoVersion -value "2015.2" -context "sdk\\\\hardware/1479935692366"
webtalk_add_data -client sdk -key Arch -value "artix7" -context "sdk\\\\hardware/1479935692366"
webtalk_add_data -client sdk -key Device -value "7a35t" -context "sdk\\\\hardware/1479935692366"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1479935692366"
webtalk_transmit -clientid 589174894 -regid "" -xml E:\\software\\Assessment_2_Traffic_Light_Ad4.0\\es3_hw_assmnt_2\\es3_hw_assmnt_2.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html E:\\software\\Assessment_2_Traffic_Light_Ad4.0\\es3_hw_assmnt_2\\es3_hw_assmnt_2.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm E:\\software\\Assessment_2_Traffic_Light_Ad4.0\\es3_hw_assmnt_2\\es3_hw_assmnt_2.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
